//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectGamesPlatformers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> DeveloperID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public string Mechanics { get; set; }
        public string Protagonist { get; set; }
        public Nullable<int> PlatformID { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
